// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.proto

#include "db.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace db {
class db_account_tab_user_accountDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<db_account_tab_user_account> _instance;
} _db_account_tab_user_account_default_instance_;
class db_account_tab_user_login_infoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<db_account_tab_user_login_info> _instance;
} _db_account_tab_user_login_info_default_instance_;
class db_accountDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<db_account> _instance;
} _db_account_default_instance_;
}  // namespace db
static void InitDefaultsdb_account_tab_user_account_db_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::db::_db_account_tab_user_account_default_instance_;
    new (ptr) ::db::db_account_tab_user_account();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::db::db_account_tab_user_account::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_db_account_tab_user_account_db_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsdb_account_tab_user_account_db_2eproto}, {}};

static void InitDefaultsdb_account_tab_user_login_info_db_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::db::_db_account_tab_user_login_info_default_instance_;
    new (ptr) ::db::db_account_tab_user_login_info();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::db::db_account_tab_user_login_info::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_db_account_tab_user_login_info_db_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsdb_account_tab_user_login_info_db_2eproto}, {}};

static void InitDefaultsdb_account_db_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::db::_db_account_default_instance_;
    new (ptr) ::db::db_account();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::db::db_account::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_db_account_db_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsdb_account_db_2eproto}, {}};

void InitDefaults_db_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_db_account_tab_user_account_db_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_db_account_tab_user_login_info_db_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_db_account_db_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_db_2eproto[3];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_db_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_db_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_db_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, account_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, userid_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, password_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, platform_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, phone_num_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, device_mac_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, register_time_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, lastlogin_time_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_account, token_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_login_info, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_login_info, user_id_),
  PROTOBUF_FIELD_OFFSET(::db::db_account_tab_user_login_info, account_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::db::db_account, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::db::db_account_tab_user_account)},
  { 14, -1, sizeof(::db::db_account_tab_user_login_info)},
  { 21, -1, sizeof(::db::db_account)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::db::_db_account_tab_user_account_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::db::_db_account_tab_user_login_info_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::db::_db_account_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_db_2eproto = {
  {}, AddDescriptors_db_2eproto, "db.proto", schemas,
  file_default_instances, TableStruct_db_2eproto::offsets,
  file_level_metadata_db_2eproto, 3, file_level_enum_descriptors_db_2eproto, file_level_service_descriptors_db_2eproto,
};

const char descriptor_table_protodef_db_2eproto[] =
  "\n\010db.proto\022\002db\"\204\002\n\ndb_account\032\274\001\n\020tab_us"
  "er_account\022\017\n\007account\030\001 \001(\t\022\016\n\006userid\030\002 "
  "\001(\003\022\020\n\010password\030\003 \001(\t\022\020\n\010platform\030\004 \001(\t\022"
  "\021\n\tphone_num\030\005 \001(\003\022\022\n\ndevice_mac\030\006 \001(\t\022\025"
  "\n\rregister_time\030\007 \001(\003\022\026\n\016lastlogin_time\030"
  "\010 \001(\003\022\r\n\005token\030\t \001(\t\0327\n\023tab_user_login_i"
  "nfo\022\017\n\007user_id\030\001 \001(\003\022\017\n\007account\030\002 \001(\tb\006p"
  "roto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_db_2eproto = {
  false, InitDefaults_db_2eproto, 
  descriptor_table_protodef_db_2eproto,
  "db.proto", &assign_descriptors_table_db_2eproto, 285,
};

void AddDescriptors_db_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_db_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_db_2eproto = []() { AddDescriptors_db_2eproto(); return true; }();
namespace db {

// ===================================================================

void db_account_tab_user_account::InitAsDefaultInstance() {
}
class db_account_tab_user_account::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int db_account_tab_user_account::kAccountFieldNumber;
const int db_account_tab_user_account::kUseridFieldNumber;
const int db_account_tab_user_account::kPasswordFieldNumber;
const int db_account_tab_user_account::kPlatformFieldNumber;
const int db_account_tab_user_account::kPhoneNumFieldNumber;
const int db_account_tab_user_account::kDeviceMacFieldNumber;
const int db_account_tab_user_account::kRegisterTimeFieldNumber;
const int db_account_tab_user_account::kLastloginTimeFieldNumber;
const int db_account_tab_user_account::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

db_account_tab_user_account::db_account_tab_user_account()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:db.db_account.tab_user_account)
}
db_account_tab_user_account::db_account_tab_user_account(const db_account_tab_user_account& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.account().size() > 0) {
    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  platform_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.platform().size() > 0) {
    platform_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.platform_);
  }
  device_mac_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.device_mac().size() > 0) {
    device_mac_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.device_mac_);
  }
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.token().size() > 0) {
    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  ::memcpy(&userid_, &from.userid_,
    static_cast<size_t>(reinterpret_cast<char*>(&lastlogin_time_) -
    reinterpret_cast<char*>(&userid_)) + sizeof(lastlogin_time_));
  // @@protoc_insertion_point(copy_constructor:db.db_account.tab_user_account)
}

void db_account_tab_user_account::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_db_account_tab_user_account_db_2eproto.base);
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  platform_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_mac_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&userid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lastlogin_time_) -
      reinterpret_cast<char*>(&userid_)) + sizeof(lastlogin_time_));
}

db_account_tab_user_account::~db_account_tab_user_account() {
  // @@protoc_insertion_point(destructor:db.db_account.tab_user_account)
  SharedDtor();
}

void db_account_tab_user_account::SharedDtor() {
  account_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  platform_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_mac_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void db_account_tab_user_account::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const db_account_tab_user_account& db_account_tab_user_account::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_db_account_tab_user_account_db_2eproto.base);
  return *internal_default_instance();
}


void db_account_tab_user_account::Clear() {
// @@protoc_insertion_point(message_clear_start:db.db_account.tab_user_account)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  platform_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_mac_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&userid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lastlogin_time_) -
      reinterpret_cast<char*>(&userid_)) + sizeof(lastlogin_time_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* db_account_tab_user_account::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<db_account_tab_user_account*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string account = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("db.db_account.tab_user_account.account");
        object = msg->mutable_account();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // int64 userid = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_userid(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string password = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("db.db_account.tab_user_account.password");
        object = msg->mutable_password();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string platform = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("db.db_account.tab_user_account.platform");
        object = msg->mutable_platform();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // int64 phone_num = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        msg->set_phone_num(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string device_mac = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 50) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("db.db_account.tab_user_account.device_mac");
        object = msg->mutable_device_mac();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // int64 register_time = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 56) goto handle_unusual;
        msg->set_register_time(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int64 lastlogin_time = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 64) goto handle_unusual;
        msg->set_lastlogin_time(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string token = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 74) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("db.db_account.tab_user_account.token");
        object = msg->mutable_token();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool db_account_tab_user_account::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:db.db_account.tab_user_account)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string account = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account().data(), static_cast<int>(this->account().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "db.db_account.tab_user_account.account"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 userid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &userid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string password = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "db.db_account.tab_user_account.password"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string platform = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_platform()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->platform().data(), static_cast<int>(this->platform().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "db.db_account.tab_user_account.platform"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 phone_num = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &phone_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string device_mac = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (50 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_device_mac()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->device_mac().data(), static_cast<int>(this->device_mac().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "db.db_account.tab_user_account.device_mac"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 register_time = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (56 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &register_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 lastlogin_time = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (64 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &lastlogin_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string token = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (74 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->token().data(), static_cast<int>(this->token().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "db.db_account.tab_user_account.token"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:db.db_account.tab_user_account)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:db.db_account.tab_user_account)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void db_account_tab_user_account::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:db.db_account.tab_user_account)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string account = 1;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), static_cast<int>(this->account().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.account");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->account(), output);
  }

  // int64 userid = 2;
  if (this->userid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->userid(), output);
  }

  // string password = 3;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->password(), output);
  }

  // string platform = 4;
  if (this->platform().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->platform().data(), static_cast<int>(this->platform().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.platform");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->platform(), output);
  }

  // int64 phone_num = 5;
  if (this->phone_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->phone_num(), output);
  }

  // string device_mac = 6;
  if (this->device_mac().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->device_mac().data(), static_cast<int>(this->device_mac().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.device_mac");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->device_mac(), output);
  }

  // int64 register_time = 7;
  if (this->register_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->register_time(), output);
  }

  // int64 lastlogin_time = 8;
  if (this->lastlogin_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->lastlogin_time(), output);
  }

  // string token = 9;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), static_cast<int>(this->token().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->token(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:db.db_account.tab_user_account)
}

::google::protobuf::uint8* db_account_tab_user_account::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:db.db_account.tab_user_account)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string account = 1;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), static_cast<int>(this->account().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.account");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->account(), target);
  }

  // int64 userid = 2;
  if (this->userid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->userid(), target);
  }

  // string password = 3;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->password(), target);
  }

  // string platform = 4;
  if (this->platform().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->platform().data(), static_cast<int>(this->platform().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.platform");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->platform(), target);
  }

  // int64 phone_num = 5;
  if (this->phone_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->phone_num(), target);
  }

  // string device_mac = 6;
  if (this->device_mac().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->device_mac().data(), static_cast<int>(this->device_mac().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.device_mac");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->device_mac(), target);
  }

  // int64 register_time = 7;
  if (this->register_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->register_time(), target);
  }

  // int64 lastlogin_time = 8;
  if (this->lastlogin_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->lastlogin_time(), target);
  }

  // string token = 9;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), static_cast<int>(this->token().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_account.token");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->token(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:db.db_account.tab_user_account)
  return target;
}

size_t db_account_tab_user_account::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:db.db_account.tab_user_account)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account = 1;
  if (this->account().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account());
  }

  // string password = 3;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  // string platform = 4;
  if (this->platform().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->platform());
  }

  // string device_mac = 6;
  if (this->device_mac().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->device_mac());
  }

  // string token = 9;
  if (this->token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->token());
  }

  // int64 userid = 2;
  if (this->userid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->userid());
  }

  // int64 phone_num = 5;
  if (this->phone_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->phone_num());
  }

  // int64 register_time = 7;
  if (this->register_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->register_time());
  }

  // int64 lastlogin_time = 8;
  if (this->lastlogin_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->lastlogin_time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void db_account_tab_user_account::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:db.db_account.tab_user_account)
  GOOGLE_DCHECK_NE(&from, this);
  const db_account_tab_user_account* source =
      ::google::protobuf::DynamicCastToGenerated<db_account_tab_user_account>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:db.db_account.tab_user_account)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:db.db_account.tab_user_account)
    MergeFrom(*source);
  }
}

void db_account_tab_user_account::MergeFrom(const db_account_tab_user_account& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:db.db_account.tab_user_account)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.account().size() > 0) {

    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.platform().size() > 0) {

    platform_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.platform_);
  }
  if (from.device_mac().size() > 0) {

    device_mac_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.device_mac_);
  }
  if (from.token().size() > 0) {

    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  if (from.userid() != 0) {
    set_userid(from.userid());
  }
  if (from.phone_num() != 0) {
    set_phone_num(from.phone_num());
  }
  if (from.register_time() != 0) {
    set_register_time(from.register_time());
  }
  if (from.lastlogin_time() != 0) {
    set_lastlogin_time(from.lastlogin_time());
  }
}

void db_account_tab_user_account::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:db.db_account.tab_user_account)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_account_tab_user_account::CopyFrom(const db_account_tab_user_account& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:db.db_account.tab_user_account)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_account_tab_user_account::IsInitialized() const {
  return true;
}

void db_account_tab_user_account::Swap(db_account_tab_user_account* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_account_tab_user_account::InternalSwap(db_account_tab_user_account* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  account_.Swap(&other->account_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  platform_.Swap(&other->platform_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  device_mac_.Swap(&other->device_mac_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  token_.Swap(&other->token_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(userid_, other->userid_);
  swap(phone_num_, other->phone_num_);
  swap(register_time_, other->register_time_);
  swap(lastlogin_time_, other->lastlogin_time_);
}

::google::protobuf::Metadata db_account_tab_user_account::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_db_2eproto);
  return ::file_level_metadata_db_2eproto[kIndexInFileMessages];
}


// ===================================================================

void db_account_tab_user_login_info::InitAsDefaultInstance() {
}
class db_account_tab_user_login_info::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int db_account_tab_user_login_info::kUserIdFieldNumber;
const int db_account_tab_user_login_info::kAccountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

db_account_tab_user_login_info::db_account_tab_user_login_info()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:db.db_account.tab_user_login_info)
}
db_account_tab_user_login_info::db_account_tab_user_login_info(const db_account_tab_user_login_info& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.account().size() > 0) {
    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  user_id_ = from.user_id_;
  // @@protoc_insertion_point(copy_constructor:db.db_account.tab_user_login_info)
}

void db_account_tab_user_login_info::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_db_account_tab_user_login_info_db_2eproto.base);
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_id_ = PROTOBUF_LONGLONG(0);
}

db_account_tab_user_login_info::~db_account_tab_user_login_info() {
  // @@protoc_insertion_point(destructor:db.db_account.tab_user_login_info)
  SharedDtor();
}

void db_account_tab_user_login_info::SharedDtor() {
  account_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void db_account_tab_user_login_info::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const db_account_tab_user_login_info& db_account_tab_user_login_info::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_db_account_tab_user_login_info_db_2eproto.base);
  return *internal_default_instance();
}


void db_account_tab_user_login_info::Clear() {
// @@protoc_insertion_point(message_clear_start:db.db_account.tab_user_login_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_id_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* db_account_tab_user_login_info::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<db_account_tab_user_login_info*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int64 user_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_user_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string account = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("db.db_account.tab_user_login_info.account");
        object = msg->mutable_account();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool db_account_tab_user_login_info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:db.db_account.tab_user_login_info)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string account = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account().data(), static_cast<int>(this->account().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "db.db_account.tab_user_login_info.account"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:db.db_account.tab_user_login_info)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:db.db_account.tab_user_login_info)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void db_account_tab_user_login_info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:db.db_account.tab_user_login_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->user_id(), output);
  }

  // string account = 2;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), static_cast<int>(this->account().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_login_info.account");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->account(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:db.db_account.tab_user_login_info)
}

::google::protobuf::uint8* db_account_tab_user_login_info::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:db.db_account.tab_user_login_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 user_id = 1;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->user_id(), target);
  }

  // string account = 2;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), static_cast<int>(this->account().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "db.db_account.tab_user_login_info.account");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->account(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:db.db_account.tab_user_login_info)
  return target;
}

size_t db_account_tab_user_login_info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:db.db_account.tab_user_login_info)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account = 2;
  if (this->account().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account());
  }

  // int64 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->user_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void db_account_tab_user_login_info::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:db.db_account.tab_user_login_info)
  GOOGLE_DCHECK_NE(&from, this);
  const db_account_tab_user_login_info* source =
      ::google::protobuf::DynamicCastToGenerated<db_account_tab_user_login_info>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:db.db_account.tab_user_login_info)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:db.db_account.tab_user_login_info)
    MergeFrom(*source);
  }
}

void db_account_tab_user_login_info::MergeFrom(const db_account_tab_user_login_info& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:db.db_account.tab_user_login_info)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.account().size() > 0) {

    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
}

void db_account_tab_user_login_info::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:db.db_account.tab_user_login_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_account_tab_user_login_info::CopyFrom(const db_account_tab_user_login_info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:db.db_account.tab_user_login_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_account_tab_user_login_info::IsInitialized() const {
  return true;
}

void db_account_tab_user_login_info::Swap(db_account_tab_user_login_info* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_account_tab_user_login_info::InternalSwap(db_account_tab_user_login_info* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  account_.Swap(&other->account_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(user_id_, other->user_id_);
}

::google::protobuf::Metadata db_account_tab_user_login_info::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_db_2eproto);
  return ::file_level_metadata_db_2eproto[kIndexInFileMessages];
}


// ===================================================================

void db_account::InitAsDefaultInstance() {
}
class db_account::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

db_account::db_account()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:db.db_account)
}
db_account::db_account(const db_account& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:db.db_account)
}

void db_account::SharedCtor() {
}

db_account::~db_account() {
  // @@protoc_insertion_point(destructor:db.db_account)
  SharedDtor();
}

void db_account::SharedDtor() {
}

void db_account::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const db_account& db_account::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_db_account_db_2eproto.base);
  return *internal_default_instance();
}


void db_account::Clear() {
// @@protoc_insertion_point(message_clear_start:db.db_account)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* db_account::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<db_account*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool db_account::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:db.db_account)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:db.db_account)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:db.db_account)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void db_account::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:db.db_account)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:db.db_account)
}

::google::protobuf::uint8* db_account::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:db.db_account)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:db.db_account)
  return target;
}

size_t db_account::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:db.db_account)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void db_account::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:db.db_account)
  GOOGLE_DCHECK_NE(&from, this);
  const db_account* source =
      ::google::protobuf::DynamicCastToGenerated<db_account>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:db.db_account)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:db.db_account)
    MergeFrom(*source);
  }
}

void db_account::MergeFrom(const db_account& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:db.db_account)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void db_account::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:db.db_account)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_account::CopyFrom(const db_account& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:db.db_account)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_account::IsInitialized() const {
  return true;
}

void db_account::Swap(db_account* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_account::InternalSwap(db_account* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata db_account::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_db_2eproto);
  return ::file_level_metadata_db_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace db
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::db::db_account_tab_user_account* Arena::CreateMaybeMessage< ::db::db_account_tab_user_account >(Arena* arena) {
  return Arena::CreateInternal< ::db::db_account_tab_user_account >(arena);
}
template<> PROTOBUF_NOINLINE ::db::db_account_tab_user_login_info* Arena::CreateMaybeMessage< ::db::db_account_tab_user_login_info >(Arena* arena) {
  return Arena::CreateInternal< ::db::db_account_tab_user_login_info >(arena);
}
template<> PROTOBUF_NOINLINE ::db::db_account* Arena::CreateMaybeMessage< ::db::db_account >(Arena* arena) {
  return Arena::CreateInternal< ::db::db_account >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
