set(libs_path ${PROJECT_SOURCE_DIR}/Libs/bin)
set(spdlog_url "https://github.com/gabime/spdlog.git")
set(openssl_url "https://github.com/openssl/openssl.git")
set(protobuf_url "https://github.com/protocolbuffers/protobuf.git")
set(mysql_url "http://cdn.tarsyun.com/src/mysql-connector-c-6.1.11-src.fixed.zip")